export const CREATE_VIDEO_DATA = "CREATE_VIDEO_DATA";
export const CREATE_VIDEO_RESPONCE_ITEM = "CREATE_VIDEO_RESPONSE_ITEM";
export const CREATE_ONLOAD = "CREATE_ONLOAD";

export const CREATE_VIDEO_PATH = "CREATE_VIDEO_PATH";
